# Generated by Django 4.2.29 on 2026-04-06 07:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_userprofile_default_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=25)),
                ('billing_address_1', models.CharField(max_length=50)),
                ('billing_address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_county', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_city', models.CharField(max_length=50)),
                ('billing_postalcode', models.CharField(blank=True, max_length=20)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_id', models.CharField(default='', max_length=254)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'cancelled'), (3, 'failed')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile')),
            ],
        ),
    ]
