# Generated by Django 4.2.29 on 2026-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'cancelled'), (3, 'failed')], default=0),
        ),
    ]
