# Generated by Django 4.2.29 on 2026-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem_download_count_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='download_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
