# Generated by Django 4.2.29 on 2026-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_orderlineitem_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
    ]
