# Generated by Django 4.2.29 on 2026-03-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='product',
            name='excerpt',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
