# Generated by Django 4.2.29 on 2026-03-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productoption_excerpt_product_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.category'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='tier',
            field=models.IntegerField(blank=True, choices=[(0, 'Starter'), (1, 'Growth'), (2, 'Pro')], null=True),
        ),
    ]
