# Generated by Django 4.2.29 on 2026-04-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productoption_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
