# Generated by Django 4.2.29 on 2026-05-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productoption_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='max_modules',
        ),
    ]
