# Generated by Django 4.2.29 on 2026-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productoption_max_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='fulfilment_choice',
            field=models.IntegerField(choices=[(0, 'Download'), (1, 'Service')]),
        ),
    ]
